apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  labels:
     app.kubernetes.io/part-of: che.eclipse.org
     app.kubernetes.io/component: workspaces-config
data:
  extensions.json: |
    {
      "recommendations": [
          "redhat.vscode-yaml",
          "ms-python.python",
          "redhat.ansible",
          "redhat.vscode-openshift-connector",
          "ms-python.black-formatter"
      ]
    }
  settings.json: |
    {
      "editor.wordWrap": "on",
      "files.autoSave": "off"
      "files.associations": {
          "*.yml": "ansible"
        },
      "ansible.ansible.path": "/usr/local/bin/ansible",
      "ansible.python.interpreterPath": "/usr/bin/python3",
      "ansible.ansible.useFullyQualifiedCollectionNames": true,
      "ansible.ansibleNavigator.path": "/usr/local/bin/ansible-navigator",
      "ansible.completion.provideModuleOptionAliases": true,
      "ansible.completion.provideRedirectModules": true,
      "ansible.validation.enabled": true,
      "ansible.validation.lint.enabled": true,
      "ansible.validation.lint.path": "/usr/local/bin/ansible-lint",
      "files.trimTrailingWhitespace": true,
      "files.trimFinalNewlines": true,
      "files.insertFinalNewline": true,
      "ansible.validation.lint.arguments": "--profile production --offline",
      "[python]": {
          "editor.defaultFormatter": "ms-python.black-formatter"
      },
      "redhat.telemetry.enabled": true,
      "ansible.executionEnvironment.containerEngine": "podman",
      "git.autofetch": true,
      "ansible.lightspeed.enabled": false,
      "terminal.integrated.scrollback": 10000,
      "openshiftToolkit.showWelcomePage": false,
      "openshiftToolkit.searchForToolsInPath": true,
      "openshiftToolkit.execMaxBufferLength": 10

    }
  configurations.json: |
    {
      "extensions.install-from-vsix-enabled": false
    }
